name: GitHub Actions Practica
on:
  push

jobs:
  Explorando-GitHub-Actions:
    runs-on: ubuntu-latest
    
    steps:
    - run: echo "El flujo de trabajo se ejecuta en el evento ${{ github.event_name }}"
    - run: echo "El trabajo se est치 ejecutando en un servidor ${{ runner.os }} hospedado en Github"
    - run: echo "El nombre de la rama es ${{ github.ref }} y tu repositorio es ${{ github.repository }}"
    - name: Verifica el c칩digo del repositorio
      uses: actions/checkout@v2
    - run: echo "el repositorio ${{ github.repository }} ha sido clonado al runner."
    - run: echo "El flujo de trabajo est치 listo para verificar el c칩digo en el runner."
    - name: Listar archivos en el repositorio
      run: |
        ls ${{ github.workspace }}
      id: list_files_in_repo
    - run: echo "El estado del trabajo es ${{ job.status }}"
